#!/bin/bash
set -x
# Script for EPG grab from WebGrab+Plus  http://www.webgrabplus.com/documentation

WEB_PATH="./"

wget -O $WEB_PATH/guide-hrt3.xml  https://raspored.hrt.hr/format/xmltv.xml?mreza=4
wait $!

function update_Main_grabber()
{
rm $WEB_PATH/pharser/libEPG-main.config
rm $WEB_PATH/wg++/WebGrab++.config.xml
#### Main EPG from Bnet Port
cp $WEB_PATH/wg++/WebGrab++.config-main.xml $WEB_PATH/wg++/WebGrab++.config.xml
cd wg++
mono WebGrab+Plus.exe "$(pwd)"
wait $!
cd ..
####### Fix channel names main
#fixchannelnames_main
wait $!
#### Generate bnet config file with python script
cp guide-main-test.xml $WEB_PATH/pharser/guide-main.xml
cd pharser
# generate main config file
##### Main pharser
python pharser-main.py
wait $!
rm guide-main.xml
cd ..
wait $!
#### Generate main config file with libEPG_xml2josn
cp guide-main-test.xml $WEB_PATH/libEPG_xml2josn/bin/Debug/guide.xml
cd $WEB_PATH/libEPG_xml2josn/bin/Debug
rm libEPG-main.config
wait $!
mono libEPG_xml2josn.exe
wait $!
cp libEPG.config libEPG-main.config
wait $!
rm guide.xml
rm libEPG.config
cd $samdec
rm guide-main-test.xml <<EOF
EOF
}

########## Mojtv ##################################

function update_Mojtv_grabber()
{
rm $WEB_PATH/pharser/libEPG-Mojtv.config
rm $WEB_PATH/wg++/WebGrab++.config.xml
#### EPG from Mojtv
cp $WEB_PATH/wg++/WebGrab++.config-mojtv.xml $WEB_PATH/wg++/WebGrab++.config.xml
cd wg++
mono WebGrab+Plus.exe "$(pwd)"
wait $!
cd ..
####### Fix channel names mojtv
#fixchannelnames_mojtv
wait $!
#### Generate mojtv config file
cp guide-mojtv-test.xml $WEB_PATH/pharser/guide-mojtv.xml
cd pharser
# generate mojtv config file
##### mojtv pharser
python pharser-mojtv.py
wait $!
rm guide-mojtv.xml
cd ..
wait $!
#### Generate mojtv config file with libEPG_xml2josn
cp guide-mojtv-test.xml $WEB_PATH/libEPG_xml2josn/bin/Debug/guide.xml
cd $WEB_PATH/libEPG_xml2josn/bin/Debug
rm libEPG-Mojtv.config
wait $!
mono libEPG_xml2josn.exe
wait $!
cp libEPG.config libEPG-Mojtv.config
wait $!
# guide.xml
rm libEPG.config
cd $samdec
rm guide-mojtv-test.xml <<EOF
EOF
}

########## a1 TV ##################################

function update_a1_grabber()
{
#### Grab EPG from A1
cp $WEB_PATH/wg++/WebGrab++.config-a1.xml $WEB_PATH/wg++/WebGrab++.config.xml
cd wg++
mono WebGrab+Plus.exe "$(pwd)"
wait $!
cd ..
rm $WEB_PATH/wg++/WebGrab++.config.xml
wait $!
#### Generate a1 config file with libEPG_xml2josn
cp guide-a1.xml $WEB_PATH/libEPG_xml2josn/bin/Debug/guide.xml
cd $WEB_PATH/libEPG_xml2josn/bin/Debug
rm libEPG-a1.config
wait $!
mono libEPG_xml2josn.exe
wait $!
cp libEPG.config libEPG-a1.config
wait $!
rm guide.xml
rm libEPG.config
### cd to previous directory
cd - <<EOF
EOF
}


########## Iskon TV ##################################

function update_iskon_grabber()
{
#### Grab EPG from Iskon TV
cp $WEB_PATH/wg++/WebGrab++.config-iskon.xml $WEB_PATH/wg++/WebGrab++.config.xml
cd wg++
mono WebGrab+Plus.exe "$(pwd)"
wait $!
cd ..
rm $WEB_PATH/wg++/WebGrab++.config.xml
wait $!
#### Generate a1 config file with libEPG_xml2josn
cp guide-iskon.xml $WEB_PATH/libEPG_xml2josn/bin/Debug/guide.xml
cd $WEB_PATH/libEPG_xml2josn/bin/Debug
rm libEPG-iskon.config
wait $!
mono libEPG_xml2josn.exe
wait $!
cp libEPG.config libEPG-iskon.config
wait $!
rm guide.xml
rm libEPG.config
### cd to previous directory
cd - <<EOF
EOF
}


############## Send to Git  ######################

function git_clone()
{
git clone --depth 1 git@github.com:muzena/webepg.git
cd  $WEB_PATH/webepg
git status
cd .. <<EOF
EOF
}

function upload_togit()
{
cd $WEB_PATH/webepg
#git add -A :/
wait $!
git commit -am "Update epg"
wait $!
git push origin master
wait $! <<EOF
EOF
}


#notify-send --app-name="Samdecrypt" --expire-time="9000" --icon="/usr/share/pixmaps/samdecrypt.png" "Generating EPG guide data started"
wait $!
#update_Main_grabber
wait $!
#update_Mojtv_grabber
wait $!
update_a1_grabber
wait $!
update_iskon_grabber
### http://www.webgrabplus.com/content/tviskonhr-and-viphr 
### http://epg.koditvepg.com/
wait $!
#sleep 10
#upload_togit
